export const CurrencySeed = [
  {
    value: 'GBP',
    country: 'United Kingdom',
    description: 'pound',
    symbol: '£',
  },
  { value: 'EUR', country: 'EU', description: 'euro', symbol: '€' },
  { value: 'USD', country: 'USA', description: 'dollar', symbol: '$' },
  { value: 'AFN', country: 'Afghanistan', description: 'afghani', symbol: '؋' },
  { value: 'ALL', country: 'Albania', description: 'lek', symbol: 'Lek' },
  { value: 'DZD', country: 'Algeria', description: 'dinar', symbol: 'دج' },
  { value: 'AOA', country: 'Angola', description: 'kwanza', symbol: 'Kz' },
  {
    value: 'XCD',
    country: 'Eastern Caribes',
    description: 'dollar',
    symbol: '$',
  },
  { value: 'ARS', country: 'Argentina', description: 'peso', symbol: '$' },
  { value: 'AMD', country: 'Armenia', description: 'dram', symbol: '֏' },
  {
    value: 'AWG',
    country: 'Aruba (Netherlands)',
    description: 'florin',
    symbol: 'ƒ',
  },
  { value: 'SHP', country: 'UK', description: 'pound', symbol: '£' },
  { value: 'AUD', country: 'Australia', description: 'dollar', symbol: '$' },
  { value: 'AZN', country: 'Azerbaijan', description: 'manat', symbol: 'm' },
  { value: 'BSD', country: 'Bahamas', description: 'dollar', symbol: 'B$' },
  { value: 'BHD', country: 'Bahrain', description: 'dinar', symbol: '.د.ب' },
  { value: 'BDT', country: 'Bangladesh', description: 'taka', symbol: '৳' },
  { value: 'BBD', country: 'Barbados', description: 'dollar', symbol: 'Bds$' },
  { value: 'BYR', country: 'Belarus', description: 'ruble', symbol: 'Br' },
  { value: 'BZD', country: 'Belize', description: 'dollar', symbol: '$' },
  {
    value: 'XOF',
    country: 'West African CFA',
    description: 'franc',
    symbol: 'CFA',
  },
  { value: 'BMD', country: 'Bermuda (UK)', description: 'dollar', symbol: '$' },
  { value: 'BTN', country: 'Bhutan', description: 'ngultrum', symbol: 'Nu.' },
  { value: 'BOB', country: 'Bolivia', description: 'boliviano', symbol: 'Bs.' },
  {
    value: 'BAM',
    country: 'Bosnia and Herzegovina',
    description: 'mark',
    symbol: 'KM',
  },
  { value: 'BWP', country: 'Botswana', description: 'pula', symbol: 'P' },
  { value: 'BRL', country: 'Brazil', description: 'real', symbol: 'R$' },
  { value: 'BND', country: 'Brunei', description: 'dollar', symbol: 'B$' },
  { value: 'BGN', country: 'Bulgaria', description: 'lev', symbol: 'Лв.' },
  { value: 'BIF', country: 'Burundi', description: 'franc', symbol: 'FBu' },
  { value: 'CVE', country: 'Cabo Verde', description: 'escudo', symbol: '$' },
  { value: 'KHR', country: 'Cambodia', description: 'riel', symbol: 'KHR' },
  {
    value: 'XAF',
    country: 'Central African CFA',
    description: 'franc',
    symbol: 'FCFA',
  },
  { value: 'CAD', country: 'Canada', description: 'dollar', symbol: '$' },
  {
    value: 'KYD',
    country: 'Cayman Islands (UK)',
    description: 'dollar',
    symbol: '$',
  },
  { value: 'NZD', country: 'New Zealand', description: 'dollar', symbol: '$' },
  { value: 'CLP', country: 'Chile', description: 'peso', symbol: '$' },
  { value: 'CNY', country: 'China', description: 'yuan', symbol: '¥' },
  { value: 'COP', country: 'Colombia', description: 'peso', symbol: '$' },
  { value: 'KMF', country: 'Comoros', description: 'franc', symbol: 'CF' },
  { value: 'CDF', country: 'Congo', description: 'franc', symbol: 'FC' },
  { value: 'CRC', country: 'Costa Rica', description: 'colon', symbol: '₡' },
  { value: 'HRK', country: 'Croatia', description: 'kuna', symbol: 'kn' },
  { value: 'CUP', country: 'Cuba', description: 'peso', symbol: '' },
  { value: 'ANG', country: 'Netherlands', description: 'guilder', symbol: 'ƒ' },
  { value: 'CZK', country: 'Czechia', description: 'koruna', symbol: 'Kč' },
  { value: 'DKK', country: 'Denmark', description: 'krone', symbol: 'Kr.' },
  { value: 'DJF', country: 'Djibouti', description: 'franc', symbol: 'Fdj' },
  {
    value: 'DOP',
    country: 'Dominican Republic',
    description: 'peso',
    symbol: '$',
  },
  { value: 'EGP', country: 'Egypt', description: 'pound', symbol: 'ج.م' },
  { value: 'ERN', country: 'Eritrea', description: 'nakfa', symbol: 'Nfk' },
  { value: 'SZL', country: 'Eswatini', description: 'lilangeni', symbol: 'E' },
  { value: 'ETB', country: 'Ethiopia', description: 'birr', symbol: 'Nkf' },
  {
    value: 'FKP',
    country: 'Falkland Islands (UK)',
    description: 'pound',
    symbol: '£',
  },
  { value: 'FJD', country: 'Fiji', description: 'dollar', symbol: 'FJ$' },
  {
    value: 'XPF',
    country: 'French Polynesia (France)',
    description: 'franc',
    symbol: '₣',
  },
  { value: 'GMD', country: 'Gambia', description: 'dalasi', symbol: 'D' },
  { value: 'GEL', country: 'Georgia', description: 'lari', symbol: 'ლ' },
  { value: 'GHS', country: 'Ghana', description: 'cedi', symbol: 'GH₵' },
  {
    value: 'GIP',
    country: 'Gibraltar (UK)',
    description: 'pound',
    symbol: '£',
  },
  { value: 'GTQ', country: 'Guatemala', description: 'quetzal', symbol: 'Q' },
  { value: 'GGP', country: 'Guernsey (UK)', description: 'pound', symbol: '' },
  { value: 'GNF', country: 'Guinea', description: 'franc', symbol: 'FG' },
  { value: 'GYD', country: 'Guyana', description: 'dollar', symbol: '$' },
  { value: 'HTG', country: 'Haiti', description: 'gourde', symbol: 'G' },
  { value: 'HNL', country: 'Honduras', description: 'lempira', symbol: 'L' },
  {
    value: 'HKD',
    country: 'Hong Kong (China)',
    description: 'dollar',
    symbol: '$',
  },
  { value: 'HUF', country: 'Hungary', description: 'forint', symbol: 'Ft' },
  { value: 'ISK', country: 'Iceland', description: 'krona', symbol: 'kr' },
  { value: 'INR', country: 'India', description: 'rupee', symbol: '₹' },
  { value: 'IDR', country: 'Indonesia', description: 'rupiah', symbol: 'Rp' },
  {
    value: 'XDR',
    country: 'International Monetary Fund',
    description: 'SDR',
    symbol: 'SDR',
  },
  { value: 'IRR', country: 'Iran', description: 'rial', symbol: '﷼' },
  { value: 'IQD', country: 'Iraq', description: 'dinar', symbol: 'د.ع' },
  {
    value: 'IMP',
    country: 'Isle of Man (UK)',
    description: 'pound',
    symbol: '',
  },
  { value: 'ILS', country: 'Israel', description: 'shekel', symbol: '₪' },
  { value: 'JMD', country: 'Jamaica', description: 'dollar', symbol: 'J$' },
  { value: 'JPY', country: 'Japan', description: 'yen', symbol: '¥' },
  { value: 'JEP', country: 'Jersey (UK)', description: 'pound', symbol: '' },
  { value: 'JOD', country: 'Jordan', description: 'dinar', symbol: 'ا.د' },
  { value: 'KZT', country: 'Kazakhstan', description: 'tenge', symbol: 'лв' },
  { value: 'KES', country: 'Kenya', description: 'shilling', symbol: 'KSh' },
  { value: 'KWD', country: 'Kuwait', description: 'dinar', symbol: 'ك.د' },
  { value: 'KGS', country: 'Kyrgyzstan', description: 'som', symbol: 'лв' },
  { value: 'LAK', country: 'Laos', description: 'kip', symbol: '₭' },
  { value: 'LBP', country: 'Lebanon', description: 'pound', symbol: '£' },
  { value: 'LSL', country: 'Lesotho', description: 'loti', symbol: 'L' },
  { value: 'LRD', country: 'Liberia', description: 'dollar', symbol: '$' },
  { value: 'LYD', country: 'Libya', description: 'dinar', symbol: 'د.ل' },
  { value: 'CHF', country: 'Switzerland', description: 'franc', symbol: 'CHf' },
  {
    value: 'MOP',
    country: 'Macau (China)',
    description: 'pataca',
    symbol: '$',
  },
  { value: 'MGA', country: 'Madagascar', description: 'ariary', symbol: 'Ar' },
  { value: 'MWK', country: 'Malawi', description: 'kwacha', symbol: 'MK' },
  { value: 'MYR', country: 'Malaysia', description: 'ringgit', symbol: 'RM' },
  { value: 'MVR', country: 'Maldives', description: 'rufiyaa', symbol: 'Rf' },
  { value: 'MRU', country: 'Mauritania', description: 'ouguiya', symbol: '' },
  { value: 'MUR', country: 'Mauritius', description: 'rupee', symbol: '₨' },
  { value: 'MXN', country: 'Mexico', description: 'peso', symbol: '$' },
  { value: 'MDL', country: 'Moldova', description: 'leu', symbol: 'L' },
  { value: 'MNT', country: 'Mongolia', description: 'tugrik', symbol: '₮' },
  { value: 'MAD', country: 'Morocco', description: 'dirham', symbol: 'MAD' },
  { value: 'MZN', country: 'Mozambique', description: 'metical', symbol: '' },
  { value: 'MMK', country: 'Myanmar', description: 'kyat', symbol: 'K' },
  { value: 'NAD', country: 'Namibia', description: 'dollar', symbol: '$' },
  { value: 'NPR', country: 'Nepal', description: 'rupee', symbol: '₨' },
  { value: 'XPF', country: 'France', description: 'franc', symbol: '₣' },
  { value: 'NIO', country: 'Nicaragua', description: 'cordoba', symbol: 'C$' },
  { value: 'NGN', country: 'Nigeria', description: 'naira', symbol: '₦' },
  { value: 'KPW', country: 'North Korea', description: 'won', symbol: '₩' },
  {
    value: 'MKD',
    country: 'North Macedonia',
    description: 'denar',
    symbol: 'ден',
  },
  { value: 'NOK', country: 'Norway', description: 'krone', symbol: 'kr' },
  { value: 'OMR', country: 'Oman', description: 'rial', symbol: '.ع.ر' },
  { value: 'PKR', country: 'Pakistan', description: 'rupee', symbol: '₨' },
  {
    value: 'PGK',
    country: 'Papua New Guinea',
    description: 'kina',
    symbol: 'K',
  },
  { value: 'PYG', country: 'Paraguay', description: 'guarani', symbol: '₲' },
  { value: 'PEN', country: 'Peru', description: 'sol', symbol: 'S/.' },
  { value: 'PHP', country: 'Philippines', description: 'peso', symbol: '₱' },
  { value: 'PLN', country: 'Poland', description: 'zloty', symbol: 'zł' },
  { value: 'QAR', country: 'Qatar', description: 'riyal', symbol: 'ق.ر' },
  { value: 'RON', country: 'Romania', description: 'leu', symbol: 'lei' },
  { value: 'RUB', country: 'Russia', description: 'ruble', symbol: '₽' },
  { value: 'RWF', country: 'Rwanda', description: 'franc', symbol: 'FRw' },
  { value: 'WST', country: 'Samoa', description: 'tala', symbol: 'SAT' },
  {
    value: 'STN',
    country: 'Sao Tome and Principe',
    description: 'dobra',
    symbol: '',
  },
  { value: 'SAR', country: 'Saudi Arabia', description: 'riyal', symbol: '﷼' },
  { value: 'RSD', country: 'Serbia', description: 'dinar', symbol: 'din' },
  { value: 'SCR', country: 'Seychelles', description: 'rupee', symbol: 'SRe' },
  { value: 'SLL', country: 'Sierra Leone', description: 'leone', symbol: 'Le' },
  { value: 'SGD', country: 'Singapore', description: 'dollar', symbol: '$' },
  {
    value: 'SBD',
    country: 'Solomon Islands',
    description: 'dollar',
    symbol: 'Si$',
  },
  {
    value: 'SOS',
    country: 'Somalia',
    description: 'shilling',
    symbol: 'Sh.so.',
  },
  { value: 'ZAR', country: 'South Africa', description: 'rand', symbol: 'R' },
  { value: 'KRW', country: 'South Korea', description: 'won', symbol: '₩' },
  { value: 'SSP', country: 'South Sudan', description: 'pound', symbol: '' },
  { value: 'LKR', country: 'Sri Lanka', description: 'rupee', symbol: 'Rs' },
  { value: 'SDG', country: 'Sudan', description: 'pound', symbol: '.س.ج' },
  { value: 'SRD', country: 'Suriname', description: 'dollar', symbol: '$' },
  { value: 'SEK', country: 'Sweden', description: 'krona', symbol: 'kr' },
  { value: 'SYP', country: 'Syria', description: 'pound', symbol: 'LS' },
  { value: 'TWD', country: 'Taiwan', description: 'dollar', symbol: '$' },
  { value: 'TJS', country: 'Tajikistan', description: 'somoni', symbol: 'SM' },
  { value: 'TZS', country: 'Tanzania', description: 'shilling', symbol: 'TSh' },
  { value: 'THB', country: 'Thailand', description: 'baht', symbol: '฿' },
  { value: 'TOP', country: 'Tonga', description: 'pa`anga', symbol: '$' },
  {
    value: 'TTD',
    country: 'Trinidad and Tobago',
    description: 'dollar',
    symbol: '$',
  },
  { value: 'TND', country: 'Tunisia', description: 'dinar', symbol: 'ت.د' },
  { value: 'TRY', country: 'Turkey', description: 'lira', symbol: '₺' },
  { value: 'TMT', country: 'Turkmenistan', description: 'manat', symbol: 'T' },
  { value: 'UGX', country: 'Uganda', description: 'shilling', symbol: 'USh' },
  { value: 'UAH', country: 'Ukraine', description: 'hryvnia', symbol: '₴' },
  {
    value: 'AED',
    country: 'United Arab Emirates',
    description: 'dirham',
    symbol: 'إ.د',
  },
  { value: 'UYU', country: 'Uruguay', description: 'peso', symbol: '$' },
  { value: 'UZS', country: 'Uzbekistan', description: 'som', symbol: 'лв' },
  { value: 'VUV', country: 'Vanuatu', description: 'vatu', symbol: 'VT' },
  { value: 'VES', country: 'Venezuela', description: 'bolivar', symbol: 'Bs' },
  { value: 'VND', country: 'Vietnam', description: 'dong', symbol: '₫' },
  { value: 'YER', country: 'Yemen', description: 'rial', symbol: '﷼' },
  { value: 'ZMW', country: 'Zambia', description: 'kwacha', symbol: '' },
];
