export const CurrencySeed = [
  { value: 'GBP', country: 'United Kingdom', description: 'pound' },
  { value: 'EUR', country: 'EU', description: 'euro' },
  { value: 'USD', country: 'USA', description: 'dollar' },
  { value: 'AFN', country: 'Afghanistan', description: 'afghani' },
  { value: 'ALL', country: 'Albania', description: 'lek' },
  { value: 'DZD', country: 'Algeria', description: 'dinar' },
  { value: 'AOA', country: 'Angola', description: 'kwanza' },
  { value: 'XCD', country: 'Eastern Caribes', description: 'dollar' },
  { value: 'ARS', country: 'Argentina', description: 'peso' },
  { value: 'AMD', country: 'Armenia', description: 'dram' },
  { value: 'AWG', country: 'Aruba (Netherlands)', description: 'florin' },
  { value: 'SHP', country: 'UK', description: 'pound' },
  { value: 'AUD', country: 'Australia', description: 'dollar' },
  { value: 'AZN', country: 'Azerbaijan', description: 'manat' },
  { value: 'BSD', country: 'Bahamas', description: 'dollar' },
  { value: 'BHD', country: 'Bahrain', description: 'dinar' },
  { value: 'BDT', country: 'Bangladesh', description: 'taka' },
  { value: 'BBD', country: 'Barbados', description: 'dollar' },
  { value: 'BYN', country: 'Belarus', description: 'ruble' },
  { value: 'BZD', country: 'Belize', description: 'dollar' },
  { value: 'XOF', country: 'West African CFA', description: 'franc' },
  { value: 'BMD', country: 'Bermuda (UK)', description: 'dollar' },
  { value: 'BTN', country: 'Bhutan', description: 'ngultrum' },
  { value: 'BOB', country: 'Bolivia', description: 'boliviano' },
  { value: 'BAM', country: 'Bosnia and Herzegovina', description: 'mark' },
  { value: 'BWP', country: 'Botswana', description: 'pula' },
  { value: 'BRL', country: 'Brazil', description: 'real' },
  { value: 'BND', country: 'Brunei', description: 'dollar' },
  { value: 'BGN', country: 'Bulgaria', description: 'lev' },
  { value: 'BIF', country: 'Burundi', description: 'franc' },
  { value: 'CVE', country: 'Cabo Verde', description: 'escudo' },
  { value: 'KHR', country: 'Cambodia', description: 'riel' },
  { value: 'XAF', country: 'Central African CFA', description: 'franc' },
  { value: 'CAD', country: 'Canada', description: 'dollar' },
  { value: 'KYD', country: 'Cayman Islands (UK)', description: 'dollar' },
  { value: 'NZD', country: 'New Zealand', description: 'dollar' },
  { value: 'CLP', country: 'Chile', description: 'peso' },
  { value: 'CNY', country: 'China', description: 'yuan' },
  { value: 'COP', country: 'Colombia', description: 'peso' },
  { value: 'KMF', country: 'Comoros', description: 'franc' },
  {
    value: 'CDF',
    country: 'Congo',
    description: 'franc',
  },
  { value: 'CRC', country: 'Costa Rica', description: 'colon' },
  { value: 'HRK', country: 'Croatia', description: 'kuna' },
  { value: 'CUP', country: 'Cuba', description: 'peso' },
  { value: 'ANG', country: 'Netherlands', description: 'guilder' },
  { value: 'CZK', country: 'Czechia', description: 'koruna' },
  { value: 'DKK', country: 'Denmark', description: 'krone' },
  { value: 'DJF', country: 'Djibouti', description: 'franc' },
  { value: 'DOP', country: 'Dominican Republic', description: 'peso' },
  { value: 'EGP', country: 'Egypt', description: 'pound' },
  { value: 'ERN', country: 'Eritrea', description: 'nakfa' },
  { value: 'SZL', country: 'Eswatini', description: 'lilangeni' },
  { value: 'ETB', country: 'Ethiopia', description: 'birr' },
  { value: 'FKP', country: 'Falkland Islands (UK)', description: 'pound' },
  { value: 'FJD', country: 'Fiji', description: 'dollar' },
  { value: 'XPF', country: 'French Polynesia (France)', description: 'franc' },
  { value: 'GMD', country: 'Gambia', description: 'dalasi' },
  { value: 'GEL', country: 'Georgia', description: 'lari' },
  { value: 'GHS', country: 'Ghana', description: 'cedi' },
  { value: 'GIP', country: 'Gibraltar (UK)', description: 'pound' },
  { value: 'GTQ', country: 'Guatemala', description: 'quetzal' },
  { value: 'GGP', country: 'Guernsey (UK)', description: 'pound' },
  { value: 'GNF', country: 'Guinea', description: 'franc' },
  { value: 'GYD', country: 'Guyana', description: 'dollar' },
  { value: 'HTG', country: 'Haiti', description: 'gourde' },
  { value: 'HNL', country: 'Honduras', description: 'lempira' },
  { value: 'HKD', country: 'Hong Kong (China)', description: 'dollar' },
  { value: 'HUF', country: 'Hungary', description: 'forint' },
  { value: 'ISK', country: 'Iceland', description: 'krona' },
  { value: 'INR', country: 'India', description: 'rupee' },
  { value: 'IDR', country: 'Indonesia', description: 'rupiah' },
  {
    value: 'XDR',
    country: 'International Monetary Fund',
    description: 'SDR',
  },
  { value: 'IRR', country: 'Iran', description: 'rial' },
  { value: 'IQD', country: 'Iraq', description: 'dinar' },
  { value: 'IMP', country: 'Isle of Man (UK)', description: 'pound' },
  { value: 'ILS', country: 'Israel', description: 'shekel' },
  { value: 'JMD', country: 'Jamaica', description: 'dollar' },
  { value: 'JPY', country: 'Japan', description: 'yen' },
  { value: 'JEP', country: 'Jersey (UK)', description: 'pound' },
  { value: 'JOD', country: 'Jordan', description: 'dinar' },
  { value: 'KZT', country: 'Kazakhstan', description: 'tenge' },
  { value: 'KES', country: 'Kenya', description: 'shilling' },
  { value: 'KWD', country: 'Kuwait', description: 'dinar' },
  { value: 'KGS', country: 'Kyrgyzstan', description: 'som' },
  { value: 'LAK', country: 'Laos', description: 'kip' },
  { value: 'LBP', country: 'Lebanon', description: 'pound' },
  { value: 'LSL', country: 'Lesotho', description: 'loti' },
  { value: 'LRD', country: 'Liberia', description: 'dollar' },
  { value: 'LYD', country: 'Libya', description: 'dinar' },
  { value: 'CHF', country: 'Switzerland', description: 'franc' },
  { value: 'MOP', country: 'Macau (China)', description: 'pataca' },
  { value: 'MGA', country: 'Madagascar', description: 'ariary' },
  { value: 'MWK', country: 'Malawi', description: 'kwacha' },
  { value: 'MYR', country: 'Malaysia', description: 'ringgit' },
  { value: 'MVR', country: 'Maldives', description: 'rufiyaa' },
  { value: 'MRU', country: 'Mauritania', description: 'ouguiya' },
  { value: 'MUR', country: 'Mauritius', description: 'rupee' },
  { value: 'MXN', country: 'Mexico', description: 'peso' },
  { value: 'MDL', country: 'Moldova', description: 'leu' },
  { value: 'MNT', country: 'Mongolia', description: 'tugrik' },
  { value: 'MAD', country: 'Morocco', description: 'dirham' },
  { value: 'MZN', country: 'Mozambique', description: 'metical' },
  { value: 'MMK', country: 'Myanmar', description: 'kyat' },
  { value: 'NAD', country: 'Namibia', description: 'dollar' },
  { value: 'NPR', country: 'Nepal', description: 'rupee' },
  { value: 'XPF', country: 'France', description: 'franc' },
  { value: 'NIO', country: 'Nicaragua', description: 'cordoba' },
  { value: 'NGN', country: 'Nigeria', description: 'naira' },
  { value: 'KPW', country: 'North Korea', description: 'won' },
  { value: 'MKD', country: 'North Macedonia', description: 'denar' },
  { value: 'NOK', country: 'Norway', description: 'krone' },
  { value: 'OMR', country: 'Oman', description: 'rial' },
  { value: 'PKR', country: 'Pakistan', description: 'rupee' },
  { value: 'PGK', country: 'Papua New Guinea', description: 'kina' },
  { value: 'PYG', country: 'Paraguay', description: 'guarani' },
  { value: 'PEN', country: 'Peru', description: 'sol' },
  { value: 'PHP', country: 'Philippines', description: 'peso' },
  { value: 'PLN', country: 'Poland', description: 'zloty' },
  { value: 'QAR', country: 'Qatar', description: 'riyal' },
  { value: 'RON', country: 'Romania', description: 'leu' },
  { value: 'RUB', country: 'Russia', description: 'ruble' },
  { value: 'RWF', country: 'Rwanda', description: 'franc' },
  { value: 'WST', country: 'Samoa', description: 'tala' },
  { value: 'STN', country: 'Sao Tome and Principe', description: 'dobra' },
  { value: 'SAR', country: 'Saudi Arabia', description: 'riyal' },
  { value: 'RSD', country: 'Serbia', description: 'dinar' },
  { value: 'SCR', country: 'Seychelles', description: 'rupee' },
  { value: 'SLL', country: 'Sierra Leone', description: 'leone' },
  { value: 'SGD', country: 'Singapore', description: 'dollar' },
  { value: 'SBD', country: 'Solomon Islands', description: 'dollar' },
  { value: 'SOS', country: 'Somalia', description: 'shilling' },
  { value: 'ZAR', country: 'South Africa', description: 'rand' },
  { value: 'KRW', country: 'South Korea', description: 'won' },
  { value: 'SSP', country: 'South Sudan', description: 'pound' },
  { value: 'LKR', country: 'Sri Lanka', description: 'rupee' },
  { value: 'SDG', country: 'Sudan', description: 'pound' },
  { value: 'SRD', country: 'Suriname', description: 'dollar' },
  { value: 'SEK', country: 'Sweden', description: 'krona' },
  { value: 'SYP', country: 'Syria', description: 'pound' },
  { value: 'TWD', country: 'Taiwan', description: 'dollar' },
  { value: 'TJS', country: 'Tajikistan', description: 'somoni' },
  { value: 'TZS', country: 'Tanzania', description: 'shilling' },
  { value: 'THB', country: 'Thailand', description: 'baht' },
  { value: 'TOP', country: 'Tonga', description: 'pa`anga' },
  { value: 'TTD', country: 'Trinidad and Tobago', description: 'dollar' },
  { value: 'TND', country: 'Tunisia', description: 'dinar' },
  { value: 'TRY', country: 'Turkey', description: 'lira' },
  { value: 'TMT', country: 'Turkmenistan', description: 'manat' },
  { value: 'UGX', country: 'Uganda', description: 'shilling' },
  { value: 'UAH', country: 'Ukraine', description: 'hryvnia' },
  { value: 'AED', country: 'United Arab Emirates', description: 'dirham' },
  { value: 'UYU', country: 'Uruguay', description: 'peso' },
  { value: 'UZS', country: 'Uzbekistan', description: 'som' },
  { value: 'VUV', country: 'Vanuatu', description: 'vatu' },
  { value: 'VES', country: 'Venezuela', description: 'bolivar' },
  { value: 'VND', country: 'Vietnam', description: 'dong' },
  { value: 'YER', country: 'Yemen', description: 'rial' },
  { value: 'ZMW', country: 'Zambia', description: 'kwacha' },
];
